"""init schema

Revision ID: ad85f1a6b411
Revises: 
Create Date: 2026-01-27 09:56:43.892574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad85f1a6b411'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('title_romaji', sa.String(), nullable=True),
    sa.Column('title_english', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('country_of_origin', sa.String(), nullable=True),
    sa.Column('mean_score', sa.Float(), nullable=True),
    sa.Column('dropped_paused', sa.Integer(), nullable=True),
    sa.Column('completed_watching', sa.Integer(), nullable=True),
    sa.Column('planning', sa.Integer(), nullable=True),
    sa.Column('variance_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('favourites', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_id'), 'anime', ['id'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('manga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('title_romaji', sa.String(), nullable=True),
    sa.Column('title_english', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('country_of_origin', sa.String(), nullable=True),
    sa.Column('mean_score', sa.Float(), nullable=True),
    sa.Column('dropped_paused', sa.Integer(), nullable=True),
    sa.Column('completed_watching', sa.Integer(), nullable=True),
    sa.Column('planning', sa.Integer(), nullable=True),
    sa.Column('variance_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('favourites', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('chapters', sa.Integer(), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manga_id'), 'manga', ['id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_spoiler', sa.Boolean(), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('anime_genres',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'genre_id')
    )
    op.create_table('anime_staff',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'staff_id')
    )
    op.create_table('anime_studio',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'studio_id')
    )
    op.create_table('anime_tag',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('is_spoiler', sa.Boolean(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'tag_id')
    )
    op.create_table('manga_genres',
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.PrimaryKeyConstraint('manga_id', 'genre_id')
    )
    op.create_table('manga_staff',
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('manga_id', 'staff_id')
    )
    op.create_table('manga_tag',
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('is_spoiler', sa.Boolean(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('manga_id', 'tag_id')
    )
    op.create_table('user_anime',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('favourite', sa.Boolean(), nullable=True),
    sa.Column('repeat', sa.Integer(), nullable=True),
    sa.Column('last_watched', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'anime_id')
    )
    op.create_table('user_manga',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('favourite', sa.Boolean(), nullable=True),
    sa.Column('repeat', sa.Integer(), nullable=True),
    sa.Column('last_read', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'manga_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_manga')
    op.drop_table('user_anime')
    op.drop_table('manga_tag')
    op.drop_table('manga_staff')
    op.drop_table('manga_genres')
    op.drop_table('anime_tag')
    op.drop_table('anime_studio')
    op.drop_table('anime_staff')
    op.drop_table('anime_genres')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tag')
    op.drop_table('studio')
    op.drop_table('staff')
    op.drop_index(op.f('ix_manga_id'), table_name='manga')
    op.drop_table('manga')
    op.drop_table('genres')
    op.drop_index(op.f('ix_anime_id'), table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
