{
 "title": "RecoMangaTion Dashboard",
 "tags": [ "linux" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "CPU / RAM usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(cpu) (node_cpu_seconds_total{job=\"node\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}" }
   ]
  },
  {
   "title": "HOST CPU usage",
   "type": "gauge",
   "description": "Occupation du CPU",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "HOST RAM usage",
   "type": "gauge",
   "description": "RAM utilisée (hors cache et memoire reclamable)",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "RAM par Services",
   "type": "bargauge",
   "description": "RAM utilisée en bytes par les services :\n- RecoManGation-api \n- Prometheus\n- Node-exporter\nMaximum : 4Go (taille de la RAM de flo)\n= 3.7252902984619 GiB",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"recoMangaTion-api\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  { "title": "RecoMangaTion-API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total User Search Requests ",
   "type": "stat",
   "description": "Nombre de requête de recherche d'ID User à partir d'un pseudo\nContient à la fois les succes et erreurs ",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(user_id_requests_total{instance=\"api:8000\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Search Requests",
   "type": "piechart",
   "description": "Nombre de requêtes de recherche d'id d'utilisateurs à partir d'un pseudo",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_id_requests_total{status=\"success\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "user_id_requests_total{status=\"error\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps du dernier Update de la DB",
   "type": "stat",
   "description": "Lorsque /update est effectué\nTemps en secondes\nSeulement le dernier",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_update_all_last_request_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence HTTP P95",
   "type": "timeseries",
   "description": "Par intervalle d'1 minute",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(http_request_duration_highr_seconds_bucket[1m])) by (le)\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requêtes HTTP / secondes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Requête par endpoint",
   "type": "timeseries",
   "description": "intervalle de une minute",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}