from .user import User
from .anime import Anime
from .manga import Manga
from .tag import Tag
from .staff import Staff
from .studio import Studio
from .genre import Genre
from .user_anime import UserAnime
from .user_manga import UserManga
from .anime_tag import AnimeTag
from .manga_tag import MangaTag
from .anime_staff import AnimeStaff
from .manga_staff import MangaStaff
from .anime_studio import AnimeStudio
from .anime_genre import AnimeGenre
from .manga_genre import MangaGenre